# Generated by Django 5.2.1 on 2025-05-24 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dimensionnement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dimensionnement',
            name='explication',
            field=models.TextField(blank=True, null=True),
        ),
    ]
